services:
- type: web
  name: ai-stock-insight
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
  envVars:
  - key: PYTHON_VERSION
    value: 3.11.9
  - key: ENV
    value: production
